/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ImageVerification__factory } from "./ImageVerification__factory";
export { TruChain__factory } from "./TruChain__factory";
